# 一、ndarray

## 1.ndarray的特性
### 多维性

In [4]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度: ', arr.ndim)  # number of dimensions

5
arr的维度:  0


In [3]:
arr = np.array([1, 2, 3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度: ', arr.ndim)  # number of dimensions

[1 2 3]
arr的维度:  1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度: ', arr.ndim)  # number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度:  2


# 同质性

In [5]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)  # '1' 和 1

['1' 'hello']


In [6]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)  # 1. 和 1

[1.  2.5]


## 2.ndarray的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状: ', arr.shape)
print('arr的维度: ', arr.ndim)
print('元素的个数: ', arr.size)
print('元素的数据类型: ', arr.dtype)
print('元素的转置: ', arr.T)

1
数组的形状:  ()
arr的维度:  0
元素的个数:  1
元素的数据类型:  int32
元素的转置:  1


In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状: ', arr.shape)
print('arr的维度: ', arr.ndim)
print('元素的个数: ', arr.size)
print('元素的数据类型: ', arr.dtype)
print('元素的转置: ', arr.T)

[1.  2.5 3. ]
数组的形状:  (3,)
arr的维度:  1
元素的个数:  3
元素的数据类型:  float64
元素的转置:  [1.  2.5 3. ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状: ', arr.shape)
print('arr的维度: ', arr.ndim)
print('元素的个数: ', arr.size)
print('元素的数据类型: ', arr.dtype)
print('元素的转置: ', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状:  (2, 3)
arr的维度:  2
元素的个数:  6
元素的数据类型:  int32
元素的转置:  [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [10]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)  # 属性
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr) # 深度拷贝
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全0 全1 未初始化
# 全0
arr = np.zeros((2, 3))
print(arr)
print(arr.dtype)
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]]
int32


In [13]:
arr = np.zeros((2,), dtype=int)
print(arr)

[0 0]


In [14]:
# 全1
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [6]:
# 未初始化
arr = np.empty((2, 3), dtype=int)
print(arr)
arr = np.empty((4, 2))
print(arr)
arr = np.full((3, 4), 2025)
print(arr)
print()

arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)

[[   1632       0       0]
 [7077985       0 7143525]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.06315134e-321]
 [1.24610723e-306 1.29061142e-306]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [16]:
# 等差数列 2 4 6 8 10
arr = np.arange(1, 10, 1)  # start,end,step(步长)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [17]:
# 等间隔数列
arr = np.linspace(1, 10, 5)
print(arr)
arr = np.linspace(0, 100, 5)
print(arr)
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]
[  0.  25.  50.  75. 100.]
[  0  25  50  75 100]


In [18]:
# 对数间隔数列
arr = np.logspace(0, 4, 2, base=2)
print(arr)
arr = np.logspace(0, 4, 3, base=2)
print(arr)
arr = np.logspace(0, 4, 3, dtype=int)  # 默认base是10
print(arr)
arr = np.logspace(0, 4, 3)
print(arr)

[ 1. 16.]
[ 1.  4. 16.]
[    1   100 10000]
[1.e+00 1.e+02 1.e+04]


In [19]:
# 特殊矩阵
# 单位矩阵:
arr = np.eye(3, dtype=int)
print(arr)
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [20]:
# 对角矩阵:
arr = np.diag([5, 1, 2, 3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [21]:
# 随机数组的生成
# 生成0到1之间的随机浮点数(均匀分布)
arr = np.random.rand(2, 3)
print(arr)

[[0.42765063 0.66386102 0.93240018]
 [0.68541416 0.0220972  0.60079131]]


In [22]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[4.06864596 4.58219358 4.07658135]
 [3.48313818 3.40343645 3.05628079]]


In [23]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[19 20 25]
 [27 11  5]]


In [24]:
# 生成随机数列(正态分布) (范围是全体实数,但大概率是-3到3)
arr = np.random.randn(2, 3)
print(arr)

[[-0.39868105 -2.03803026  0.35595428]
 [ 0.42914279 -1.82002629 -1.07190319]]


In [25]:
# 设置随机种子(设置相同种子则能固定随机数序列)
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4.ndarray的数据类型
### 布尔类型 bool

### 整数类型 int uint

### 浮点数  float

### 复数    complex


In [26]:
arr = np.array([1, 0, 1, -1, 2, 0], dtype='bool')
print(arr)

[ True False  True  True  True False]


In [27]:
arr = np.array([1, 0, 127, 0], dtype=np.int8)  # 最大127
print(arr)

[  1   0 127   0]


## 5.索引与切片

In [28]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [29]:
print(arr[10])
print(arr[:])
print(arr[2:5])
print(arr[slice(2, 15, 3)])
print(arr[arr > 10])
print(arr[(arr > 10) & (arr < 70)])
print(arr[(arr > 90) | (arr < 10)])

26
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 99 27 14 76 59 26 75 76 62 78 84 58 95 33]
[17 63 17 27 14 59 26 62 58 33]
[ 8 99  7  4 95]


In [30]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [31]:
print(arr[1, 3])
print(arr[1][3])
print(arr[:, :])
print(arr[1, :])
print(arr[1, 2:5])
print(arr[arr > 50])
print(arr[2])
print(arr[2][arr[2] > 50])
print(arr[:, 3])

91
91
[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]
[17 19 80 91 60 72 76 30]
[80 91 60]
[76 78 80 91 60 72 76 64 79 94 79 95 71 53]
[46  7 64 79 25 19 94 34]
[64 79 94]
[19 91 79  4]


## 6.ndarray的运算

In [32]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# a=[1, 2, 3]
# b=[4, 5, 6]
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


In [33]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)
# print(c-d)

[1, 2, 3, 4, 5, 6]


In [34]:
# 算术运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[0 0 0]
 [0 0 0]
 [7 4 3]]
[[1 2 3]
 [4 5 6]
 [0 0 0]]
[[       1       32      729]
 [   16384   390625 10077696]
 [       7       64      729]]


In [35]:
# 数组与标量之间的算术运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [36]:
# 广播机制
a = np.array([1, 2, 3])  # 1*3
b = np.array([[4], [5], [6]])  # 3*1
print(a + b)
print(b - a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [37]:
# a=np.array([1,2,3]) # 1*3
# b=np.array([4,5])
# print(a+b)

In [38]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = (np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]]))
print(a * b)
print(a @ b)

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 二、numpy中的常用函数
## 1.基本数学函数

In [39]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [40]:
# 计算指数 e^x=y
print(np.exp(1))  # e
print(np.exp(0))  # e

2.718281828459045
1.0


In [41]:
# 计算自然对数 lny=x
print(np.log(2.71))

0.9969486348916096


In [42]:
# 计算正弦值、余弦值
print(np.sin(np.pi))
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.2246467991473532e-16
1.0
-1.0


In [43]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [44]:
# 计算a的b次幂
print(np.power(arr, 2))

[1 1 4 9]


In [45]:
# 四舍五入
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [46]:
# 向上取整,向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [47]:
# 检测缺失值
np.isnan([1, 2, 3])
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

## 2.统计函数

求和、计算平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差

In [48]:
arr = np.random.randint(1, 20, 8)
print(arr)

[15  5 12  9  7 16 19 15]


In [49]:
# 求和
print(np.sum(arr))

98


In [50]:
# 计算平均值
print(np.mean(arr))

12.25


In [51]:
# 计算中位数
print(np.median(arr))

13.5


In [52]:
# 计算标准差、方差
print(np.var([1, 2, 3]))
print(np.std([1, 2, 3]))

0.6666666666666666
0.816496580927726


In [53]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.argmin(arr))
print(np.min(arr), np.argmin(arr))

[15  5 12  9  7 16 19 15]
19 6
1
5 1


In [77]:
# 分位数(不同方法得到的结果可能不一样)
# 中位数
print(np.median([1, 2, 3]))
print(np.median([1, 2, 3, 4]))
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(type(arr))
print(np.median(arr))
print(np.percentile(arr, 50))
print(np.percentile(arr, 20))
print(np.percentile(arr, 0))
print(np.percentile(arr, 100))
print(np.percentile(arr, 25))

2.0
2.5
[44 47 64 67]
<class 'numpy.ndarray'>
55.5
55.5
45.8
44.0
67.0
46.25


In [75]:
# 累计和、累积积
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.prod(arr))
print(np.cumprod(arr))

6
[1 3 6]
6
[1 2 6]


## 比较函数
### 比较是否大于、小于、等于
### 逻辑与、或、非
### 检查数组中是否有一个True,是否所有的都为True,自定义条件

In [72]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7], 4))
# 是否小于
print(np.less([3, 4, 5, 6, 7, 8], 4))
# 是否等于
print(np.equal([3, 4, 5, 6, 7, 8], 4))
print(np.equal([3, 4, 5], [4, 4, 4]))
# print(np.equal([3,4,5],[4,4,3,4]))

[False False  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]


In [78]:
print(np.logical_and([1, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 0]))
print(np.logical_not([1, 0]))

[ True False]
[ True False]
[False  True]


In [58]:
# 检查元素是否至少有一个元素为True
print(np.any([0, 0, 0, 0, 0]))
print(np.any([0, 0, 0, 1, 0]))
# 检查是否全部元素为True
print(np.all([1, 1, 0, 0, 0]))
print(np.all([1, 1, 1]))

False
True
False
True


In [79]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件的))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr+1, 0))

[0 0 0 5 6]


In [60]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr < 3, 1, 0))

[1 1 0 0 0]


In [61]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score >= 60, '及格', '不及格'))

[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [62]:
print(np.where(
    score < 60, '不及格', np.where(
        score < 80, '良好', '优秀'
    )
))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [81]:
# np.select(条件,返回的结果)
print(np.select([score > 80, (score >= 60) & (score < 80), score < 60],
                ['优秀', '良好', '不及格']))
print(np.select([score > 80, (score >= 60) & (score < 80), score < 50],
                ('优秀', '良好', '不及格'),
                default='未知'))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']
['未知' '优秀' '未知' '良好' '良好' '优秀' '良好' '未知' '良好' '良好' '良好' '未知' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


## 排序函数

In [85]:
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
print(arr.sort())
print(arr)

print()

np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(np.sort(arr))
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
None
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]

[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


## 去重函数

In [65]:
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


## 数组的拼接

In [66]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(np.concatenate((arr1, arr2)))

[5 7 9]
[1 2 3 4 5 6]


## 数组的分割

In [67]:
print(np.split(arr, [6, 12, 18]))
print(np.split(arr, 4))

[array([45, 48, 65, 68, 68, 10]), array([84, 22, 37, 88, 71, 89]), array([89, 13, 59, 66, 40, 88]), array([47, 89])]
[array([45, 48, 65, 68, 68]), array([10, 84, 22, 37, 88]), array([71, 89, 89, 13, 59]), array([66, 40, 88, 47, 89])]


## 调整数组的形状

In [68]:
print(np.reshape(arr, (4, 5)))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
